# Generated by Django 4.0.2 on 2023-05-11 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mengajar',
            new_name='Pengajar',
        ),
    ]
