# Generated by Django 4.0.2 on 2023-05-11 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0002_rename_mengajar_pengajar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('M', 'Mahasiswa'), ('D', 'Dosen')], default='M', max_length=2),
        ),
        migrations.CreateModel(
            name='Peminatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(choices=[('M', 'Mahasiswa'), ('P', 'Dosen'), ('K', 'Komputasi')], default='M', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminatan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
