# Generated by Django 4.0.2 on 2023-05-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0003_alter_user_role_peminatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='name',
            field=models.CharField(default='test-run', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peminatan',
            name='nama',
            field=models.CharField(choices=[('M', 'Murni'), ('P', 'Pemodelan'), ('K', 'Komputasi')], max_length=2),
        ),
    ]
